# Botのトークン
token: TOKEN_IS_HERE
# 認証用チャンネルID
channelId: 640391038510301184
# サーバーの招待リンク
inviteLink: https://discord.gg/WudKwEj
# 認証した際に設定するグループ名
authedGroup: sabamin
# 認証した際に実行するコマンド (コンソールから実行)。 {replace:player_name} でプレイヤー名に置き換え。 {replace:player_uuid} でプレイヤーのUUIDに置き換え。
# typeをconsoleに設定するとコンソールから実行。playerと設定すると認証をしたプレイヤーが実行。
runCommands:
  - command: say {replace:player_name} さんが認証しました！
    type: console
  - command: say {replace:player_name} さんが認証しました！
    type: player
# Supabase認証用のキーとエンドポイントURL
supabase:
  serviceKey: 'your key here'
  requestURI: 'your uri here'
# 認証済みのユーザー
authedUsers: